### ISSUE TITLE
Bulk Redactor is crashing when running on a particular file

### ISSUE THREAD

**Issue by WPChrisG** [Nuix/Bulk-Redactor#2]
Hi,
We have incorporated this into our larger code and when it hits a certain type of file it will completely crash out and then cause our code to trip over.

I have managed to make up some dummy data and have emailed the file to Cameron if you could please take a look if there is a way to make this not completely trip over when it encounters an issue?

I can confirm it happens in the api and when I run it in workstation. When I run the inbuilt Nuix redact it will pick up the TFN with no issue and apply markup.

Thanks,

Chris

Error below

Exception processing item with GUID 63fc0303-8889-4d8d-ac67-dc77b795c916, Invalid font name (See Nuix logs for more detail)
Cleaning up temp directory G:\03_Cases\Case 3\TemporaryPDFs
Error occured in provided block:
Unable to delete file: G:\03_Cases\Case 3\TemporaryPDFs\63f\c03\63fc0303-8889-4d8d-ac67-dc77b795c916.pdf
java.io.IOException: Unable to delete file: G:\BT_Earthrise_POC\03_Cases\Case 3\TemporaryPDFs\63f\c03\63fc0303-8889-4d8d-ac67-dc77b795c916.pdf
	at org.apache.commons.io.FileUtils.forceDelete(org/apache/commons/io/FileUtils.java:2381)
	at org.apache.commons.io.FileUtils.cleanDirectory(org/apache/commons/io/FileUtils.java:1679)
	at org.apache.commons.io.FileUtils.deleteDirectory(org/apache/commons/io/FileUtils.java:1575)
	at org.apache.commons.io.FileUtils.forceDelete(org/apache/commons/io/FileUtils.java:2372)
	at org.apache.commons.io.FileUtils.cleanDirectory(org/apache/commons/io/FileUtils.java:1679)
	at org.apache.commons.io.FileUtils.deleteDirectory(org/apache/commons/io/FileUtils.java:1575)
	at org.apache.commons.io.FileUtils.forceDelete(org/apache/commons/io/FileUtils.java:2372)
	at org.apache.commons.io.FileUtils.cleanDirectory(org/apache/commons/io/FileUtils.java:1679)
	at org.apache.commons.io.FileUtils.deleteDirectory(org/apache/commons/io/FileUtils.java:1575)
	at com.nuix.superutilities.export.PdfWorkCache.cleanupTemporaryPdfs(com/nuix/superutilities/export/PdfWorkCache.java:88)
	at com.nuix.superutilities.annotations.BulkRedactor.findAndMarkup(com/nuix/superutilities/annotations/BulkRedactor.java:312)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(jdk/internal/reflect/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(jdk/internal/reflect/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:566)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:426)
	at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:293)
	at RUBY.<main>(C:\Users\PAM-A008CE_admin01\AppData\Roaming\Nuix\Scripts\Bulk-Redactor-master\Ruby\BulkRedactor.nuixscript\BulkRedactor.rb:218)
	at org.jruby.RubyProc.call(org/jruby/RubyProc.java:318)
	at org.jruby.javasupport.Java$ProcToInterface.callProc(org/jruby/javasupport/Java.java:1136)
	at org.jruby.javasupport.Java$ProcToInterface.access$300(org/jruby/javasupport/Java.java:1113)
	at org.jruby.javasupport.Java$ProcToInterface$ConcreteMethod.call(org/jruby/javasupport/Java.java:1174)
	at com.nuix.nx.dialogs.ProgressDialog.forBlock(com/nuix/nx/dialogs/ProgressDialog.java:421)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(jdk/internal/reflect/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(jdk/internal/reflect/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:566)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:426)
	at org.jruby.javasupport.JavaMethod.invokeStaticDirect(org/jruby/javasupport/JavaMethod.java:358)
	at RUBY.<main>(C:\Users\PAM-A008CE_admin01\AppData\Roaming\Nuix\Scripts\Bulk-Redactor-master\Ruby\BulkRedactor.nuixscript\BulkRedactor.rb:182)
	at org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:1240)
	at org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:1244)
	at org.jruby.embed.internal.EmbedEvalUnitImpl.run(org/jruby/embed/internal/EmbedEvalUnitImpl.java:118)
	at org.jruby.embed.jsr223.JRubyEngine.eval(org/jruby/embed/jsr223/JRubyEngine.java:118)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(jdk/internal/reflect/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(jdk/internal/reflect/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:566)
	at com.nuix.script.e.a(com/nuix/script/SourceFile:62)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.nuix.script.e.a(com/nuix/script/SourceFile:59)
	at com.sun.proxy.$Proxy74.eval(com/sun/proxy/$Proxy74)
	at com.nuix.script.a.a(com/nuix/script/SourceFile:290)
	at com.nuix.investigator.script.m.e(com/nuix/investigator/script/SourceFile:323)
	at com.nuix.investigator.script.m.c(com/nuix/investigator/script/SourceFile:274)
	at com.nuix.investigator.script.m.doInBackground(com/nuix/investigator/script/SourceFile:177)
	at javax.swing.SwingWorker$1.call(javax/swing/SwingWorker.java:304)
	at java.util.concurrent.FutureTask.run(java/util/concurrent/FutureTask.java:264)
	at javax.swing.SwingWorker.run(javax/swing/SwingWorker.java:343)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java/util/concurrent/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java/util/concurrent/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java/lang/Thread.java:834)

**Comment by JuicyDragon** [comment]
Hello @WPChrisG there is an updated version of the script available for download here:
https://github.com/Nuix/Bulk-Redactor/releases/tag/v1.4.0

I've put some exception handling around the area in question so at least it should handle the error better.  As to why that error is happening I am uncertain, but at least it should deal with it better.

Since you are making use of this in your own code, you probably really need to update the copy of SuperUtilities.jar you use as the interface to the BulkRedactor class hasn't been modified.

**Comment by WPChrisG** [comment]
Thanks, This is letting the process not crash and continue on so we are happy with that. Appreciate the fix.
